### PR TITLE
Initial Deployment

### PR DESCRIPTION
**Pull request by sandertyu**
I'm not sure if we want to create some release files like we have done for `ckeditor-binder-plugin`, but here's a PR for the initial deployment of the plugins.

### CODE REVIEW

**Comment by moorepants** [comment]
@Miniland1333 the others need help on making sure this digital ocean deploy script is correct and we need you to verify that the adapt is working correctly (we aren't seeing that it displays anything special).

**Comment by Miniland1333** [comment]
I think the dodeploy.yml file looks acceptable, though I do see that you ckeditor-binder-plugin has this additional code you may want to include:
```yml
    - name: Bump version number
      run: |
        VERSION=$(ls release/ | sort | tail -n1 | sed 's/\.md$//')
        DATE=$(TZ='America/Los_Angeles' date -I)
        VERSION_STR="Release: $VERSION - Date: $DATE"
        sed -i "s/Development Version/$VERSION_STR/" src/scripts/activateThebelab.js
        sed -i "s/0\.0\.0/$VERSION/" package.json
```
I will need to obtain login credentials to verify, but it looks like the plugin is working properly at https://query.libretexts.org/Development/Query_Plugin_Demo
image
Those are Adapt's login fields that you are seeing, and I am meeting with Adapt's developer so he can verify it works.

**Comment by sandertyu** [comment]
> I think the dodeploy.yml file looks acceptable, though I do see that you ckeditor-binder-plugin has this additional code you may want to include:
> 
> ```yaml
>     - name: Bump version number
>       run: |
>         VERSION=$(ls release/ | sort | tail -n1 | sed 's/\.md$//')
>         DATE=$(TZ='America/Los_Angeles' date -I)
>         VERSION_STR="Release: $VERSION - Date: $DATE"
>         sed -i "s/Development Version/$VERSION_STR/" src/scripts/activateThebelab.js
>         sed -i "s/0\.0\.0/$VERSION/" package.json
> ```
> 
> I will need to obtain login credentials to verify, but it looks like the plugin is working properly at https://query.libretexts.org/Development/Query_Plugin_Demo
> image
> Those are Adapt's login fields that you are seeing, and I am meeting with Adapt's developer so he can verify it works.

Thanks for the info Henry! I think we'll wait until someone can get a pic of the plugin with proper credentials and then add it to the README. 

I've added release notes and inserted the console version number script. I'll take a look at the current branch conflicts.

**Comment by sandertyu** [comment]
Merge conflicts are fixed.

**Comment by Miniland1333** [comment]
image

Here's an example of what it will look like once a user is authenticated. It is intentionally visually quite similar to what the Query plugin does.

**Comment by sandertyu** [comment]
Fixed dodeploy and included an example image in the README

**Comment by moorepants** [comment]
@Miniland1333 I know you spoke to Noah about this, but we (or I) were confused as to why the adapt button showed up  on chem.libretexts.org before we merged this to the main branch. I was under the impression that merging to staging deploys the plugins to query.libretexts.org and that merging to main deploys to chem.libretexts.org (and the other "production" sites). What actually does happen on deployment? We need to know so that we aren't deploying things accidentally to the production sites, which seemed to happen in this case.

**Comment by Miniland1333** [comment]
You are completely correct.

What had happened was that we were linking the test.libretexts.org (staging version) so that Delmar could actively Beta test it on Chemistry. Since the deployment on the Query + adapt plugins has taken a while, this has actually been set up like this for the past 4 months. I should have been more aggressive in getting this plugin deployed earlier rather than having such an open-ended beta period.

After lunch, I will swap over the script links from test.libretexts.org to the CDN, so that only future releases to main/master will result in production changes.

**Comment by moorepants** [comment]
Ok, please inform us about these beta tests. This is the first I've heard of it.

> After lunch, I will swap over the script links from test.libretexts.org to the CDN, so that only future releases to main/master will result in production changes.

Thanks.

**Comment by Miniland1333** [comment]
For future beta tests (if we even ever make more plugins), I will try to use username localization so that it is a closed beta. I was not planning on that previous beta being longer than a few days but we all got busy with other priorities during winter quarter.

**Comment by moorepants** [comment]
I thought that deploying to query.libretexts.org allows anyone with a login there to test the features we add to ckeditor plugin. My understanding of the process is:

1. We edit the plugins and test them locally on a feature branch.
2. Make a pull request to staging branch, get a review.
3. Merge PR and deployment action from staging branch to query.libretexts.org.
4. Log into query.libretexts.org and test there. Also inform other libretexts users to try it out.
5. If all is well, merge staging into master.
6. Master deployment action will push to "production" (chem.libretexts, stats.libretexts.org, etc).

I thought the purpose of pushing to query.libretexts.org is so that we can test things out without affecting any users.

**Comment by Miniland1333** [comment]
Yes, this is the workflow we followed. The only modification is that as step 4.5 we had the plugin loaded for Delmar on the chemistry main library since we wanted to ensure the query plugin operated acceptably in a cross-site manner. Testing the query plugin on Query is same-site, so there was a good chance that the behavior might have been different due to API authentication and such.

In the event a future plugin requires a cross-site beta, I will ensure it is closed to only the users who are explicitly testing the plugin out on the cross-site and that the beta has a fixed length before deployment. This was the first time our plugin required cross-site testing, and I agree that these changes are necessary in the future so that end-users aren’t impacted during development.

**Pull request merged**
